### ISSUE TITLE
[Checklist] Upgrade SVN to 2.1.1

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/cta#43]
Check list for new version deploy
- [x]  Update main file version numbers
- [x]  Update readme.txt & change log from viewing closed github issues. 
- [x]  Update change log on http://docs.inboundnow.com/changelogs/calls-to-action/
- [x] Test new version installation against older released versions of Leads & LP
- [x]  Make sure all landing pages & variations are in tact.
- [x]  Manual Unit Tests
  - [x] Make sure calls to action & cta variations remain in tact
  - [x] Make sure calls to action load in preview
  - [x] Make sure calls to action load as dynamic placement
  - [x] Make sure calls to action load as static widget placement
  - [x] Make sure calls to action variations are recording impressions
  - [x] Make sure calls to action are recording conversions (click & forms submissions)
  - [x] Make sure calls to action customizer works.
  - [x] Make sure calls to action clone feature works
- [x]  Install latest lp & leads & repeat manual unit tests above. 
- [x]  Deploy plugin update. 
- [ ]  Announce plugin update to Twitter.
- [ ]  Announce plugin update to Facebook. 
- [ ]  Announce plugin update to Email?
